[package]
name = "wordle-wordlists-data"
edition.workspace = true
version.workspace = true

[dependencies]
wordle-wordlists-processing = {path = "../wordlists-processing"}
common_macros.workspace = true