[package]
name = "wordle-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wordle"
path = "src/main.rs"

[lib]
name = "wordle_tui"

[dependencies]
wordle-game = { path = "../game" }
ratatui = "0.29"
crossterm = "0.28"
